name: Deployment
on: workflow_call
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.17.6'
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 Deployment done."
